# Generated by Django 2.2 on 2019-11-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='floor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='information',
            name='room',
            field=models.IntegerField(),
        ),
    ]
