# Generated by Django 2.2 on 2019-11-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191102_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
