# Generated by Django 2.2 on 2019-11-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191104_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='branch1',
            new_name='branch',
        ),
        migrations.AlterField(
            model_name='information',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In progress', 'In progress'), ('Done', 'Done')], max_length=30),
        ),
    ]
