# Generated by Django 2.2.4 on 2019-11-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_list', models.CharField(choices=[('SPIDERMAN', 'Spiderman'), ('IRONMAN', 'Ironman'), ('BLACK PANTHER', 'Black Panther'), ('SPIDERMAN2', 'Spiderman2'), ('CAPTAIN AMERICA', 'Captain America')], max_length=100)),
                ('age', models.CharField(choices=[('UNDER 18', 'Under 18'), ('45-54', '45-54'), ('35-44', '35-44'), ('25-34', '25-34'), ('18-24', '18-24'), ('55-64', '55-64'), ('ABOVE 64', 'Above 64')], max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=100)),
            ],
        ),
    ]
